const express = require("express");
const cors = require("cors");
const bcrypt = require("bcryptjs");
require("dotenv").config();
const mongoose = require("mongoose");

const app = express();

const PORT = 3000;

mongoose
  .connect(process.env.MONGODB_URI)
    .then(() => {
        console.log("MongoDB connected successfully!");
          })
            .catch((error) => {
                console.error("MongoDB connection failed:", error);
                  });

// Middleware
app.use(cors());
app.use(express.json());

// Serve frontend files
app.use(express.static(__dirname));


// Temporary user storage
const users = [];


// Home page
app.get("/", (req, res) => {
    res.sendFile(__dirname + "/index.html");
    });


    // Health check
    app.get("/api/health", (req, res) => {
        res.json({
                success: true,
                        message: "Placement Tracker backend is running 🚀"
                            });
                            });


                            // REGISTER API
                            app.post("/api/register", async (req, res) => {

                                try {

                                        const { name, email, password } = req.body;

                                                if (!name || !email || !password) {
                                                            return res.status(400).json({
                                                                            success: false,
                                                                                            message: "Name, email and password are required."
                                                                                                        });
                                                                                                                }

                                                                                                                        if (password.length < 6) {
                                                                                                                                    return res.status(400).json({
                                                                                                                                                    success: false,
                                                                                                                                                                    message: "Password must contain at least 6 characters."
                                                                                                                                                                                });
                                                                                                                                                                                        }

                                                                                                                                                                                                const existingUser = users.find(
                                                                                                                                                                                                            user => user.email === email.toLowerCase()
                                                                                                                                                                                                                    );

                                                                                                                                                                                                                            if (existingUser) {
                                                                                                                                                                                                                                        return res.status(409).json({
                                                                                                                                                                                                                                                        success: false,
                                                                                                                                                                                                                                                                        message: "Email is already registered."
                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                    const hashedPassword =
                                                                                                                                                                                                                                                                                                                await bcrypt.hash(password, 10);

                                                                                                                                                                                                                                                                                                                        const newUser = {
                                                                                                                                                                                                                                                                                                                                    id: Date.now(),
                                                                                                                                                                                                                                                                                                                                                name: name,
                                                                                                                                                                                                                                                                                                                                                            email: email.toLowerCase(),
                                                                                                                                                                                                                                                                                                                                                                        password: hashedPassword
                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                        users.push(newUser);

                                                                                                                                                                                                                                                                                                                                                                                                res.status(201).json({
                                                                                                                                                                                                                                                                                                                                                                                                            success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                        message: "Account created successfully! 🎉",
                                                                                                                                                                                                                                                                                                                                                                                                                                    user: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    id: newUser.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name: newUser.name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    email: newUser.email
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error(error);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res.status(500).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        success: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    message: "Server error."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // VERSION 6C - LOGIN API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ==========================================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.post("/api/login", async (req, res) => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const { email, password } = req.body;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Validate input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!email || !password) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return res.status(400).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        success: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        message: "Email and password are required."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Find user
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const user = users.find(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        user => user.email === email.toLowerCase()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // User not found
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!user) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return res.status(401).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            success: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            message: "Invalid email or password."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Check password
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const passwordMatch =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await bcrypt.compare(password, user.password);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!passwordMatch) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return res.status(401).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                success: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                message: "Invalid email or password."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Login successful
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.json({

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                success: true,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            message: "Login successful! 🎉",

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        user: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        id: user.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        name: user.name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        email: user.email
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    catch (error) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error(error);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.status(500).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                success: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            message: "Server error."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Start server
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.listen(PORT, () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log(`Server running on port ${PORT}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });